version: "3.5"
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - 80:80
    networks:
      - nginx
    depends_on:
      - php
      - mysql
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - nginx
  mysql:
    image: mysql:5.7.8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
    - 3306:3306
    networks:
      - nginx
    volumes:
    - mysql_data:/var/lib/mysql


networks:
  nginx:
    driver: bridge
volumes:
  mysql_data:
